### ISSUE TITLE
spawn pnpx ENOENT

### ISSUE THREAD

**Issue by takoyaro** [svelte-add/tailwindcss#45]
While running `npx svelte-add tailwindcss` , I get the following error:
```js
 errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn pnpx',
  path: 'pnpx',
  spawnargs: [
    '--yes',
    '--ignore-existing',
    'apply',
    'svelte-add/tailwindcss',
    '--jit',
    'false',
    '--no-ssh'
  ]
```

I figured there might be something wrong with my environment since I also happen to have pnpm installed and tried running:
`pnpx svelte-add tailwindcss` but still end up with the same error.

Command was running fine yesterday though, must have been caused by recent updates.

**Comment by babichjacob** [comment]
Does `pnpm --version` result in an output or an error?

I might've made a mistake with how `pnpx`'s availability is detected.

**Comment by babichjacob** [comment]
Wait, how do you have `pnpm` available but not `pnpx`?

**Comment by takoyaro** [comment]
> ~Wait, how do you have `pnpm` available but not `pnpx`?~
> 
> I'm extremely confused. It should not be possible for you to run `pnpx ...` in the terminal but for the script not to be able to.

I'm just as confused 😓
`pnpm` output:
![image](https://user-images.githubusercontent.com/54836677/119280677-619bf500-bc6d-11eb-950b-023fe48e8455.png)

`pnpx` output: 
![image](https://user-images.githubusercontent.com/54836677/119280738-9dcf5580-bc6d-11eb-9190-f259908d34c9.png)

**Comment by f-elix** [comment]
If it helps, I get the exact same error but with `npx`, so I don't think the problem is related to `pnpx`.

**Comment by babichjacob** [comment]
> so I don't think the problem is related to `pnpx`.

It is. There is a function inside of `svelte-add` that starts `pnpx` if `pnpm` is installed even if you ran the command with `npx`.

**Comment by f-elix** [comment]
`events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [
    '--yes',
    '--ignore-existing',
    'apply',
    'svelte-add/tailwindcss',
    '--jit',
    'false',
    '--no-ssh'
  ]
}`

This is the output I get. Same error but with `spawn npx` instead of `spawn pnpx`. I just tested with the postcss adder as well and it gives me the exact same error output. Hope this helps.

**Comment by babichjacob** [comment]
Wait, are you on Windows? This may be related to https://github.com/ionic-team/capacitor-angular-toolkit/pull/11/files

**Comment by takoyaro** [comment]
Looks like you're right. Running the command on WSL solves the issue.

![image](https://user-images.githubusercontent.com/54836677/119281261-08819080-bc70-11eb-9a77-1f8d65d47dc4.png)
