### ISSUE TITLE
svelte-add tailwind error

### ISSUE THREAD

**Issue by Agedjus** [svelte-add/tailwindcss#49]
Hi,

Just to follow up with #46, now it shows a message with latest version of svelte-add:

```
~/code/website$ npx svelte-add tailwindcss --jit
npx: installed 61 in 3.354s
➕ Svelte Add
The project directory you're giving to this command cannot be guaranteed to be fresh. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

tailwindcss
  ❌ `tailwindcss` is installed
  ❌ `postcss.config.cjs` has `tailwindcss` as a plugin

  ❌ was supposed to be set up for you but it appears not to have been?! (see above)
This is definitely not supposed to happen, so please create or find an existing issue at https://github.com/svelte-add/svelte-add/issues with the full command output.
```

**Comment by quantuminformation** [comment]
I'm getting

```
npx svelte-add tailwindcss  # --jit

npx: installed 61 in 5.985s
➕ Svelte Add
The project directory you're giving to this command cannot be guaranteed to be fresh. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

tailwindcss
(node:5911) UnhandledPromiseRejectionWarning: Error: npx: command not found: use-preset

    at Socket.<anonymous> (file:///Users/nikos/.npm/_npx/5911/lib/node_modules/svelte-add/index.js:310:10)
```

**Comment by sw-yx** [comment]
interesting i get a different error: `(node:49184) UnhandledPromiseRejectionWarning: Error: Install for [ 'github:svelte-add/tailwindcss' ] failed with code 1`

**Comment by babichjacob** [comment]
> I'm getting
> 
> ```
> npx svelte-add tailwindcss  # --jit
> 
> npx: installed 61 in 5.985s
> ➕ Svelte Add
> The project directory you're giving to this command cannot be guaranteed to be fresh. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.
> 
> tailwindcss
> (node:5911) UnhandledPromiseRejectionWarning: Error: npx: command not found: use-preset
> 
>     at Socket.<anonymous> (file:///Users/nikos/.npm/_npx/5911/lib/node_modules/svelte-add/index.js:310:10)
> ```

Thanks for the report, this has been fixed by https://github.com/svelte-add/svelte-add/commit/5592111ca40dfa81492165ec09fef81c3c9ee400


I'm not sure what's going on with the other two besides asking for patience as I rewrite the Tailwind CSS adder (and its dependent PostCSS adder).

**Comment by quantuminformation** [comment]
looks good

![image](https://user-images.githubusercontent.com/216566/121157109-900ef800-c849-11eb-8363-45ae454f5570.png)

![image](https://user-images.githubusercontent.com/216566/121157182-9e5d1400-c849-11eb-9f70-51119957effa.png)


shouldnt .postcss be .pcss ?

**Comment by babichjacob** [comment]
> shouldnt .postcss be .pcss ?

No, because Vite doesn't understand `.pcss` for PostCSS. It only recognizes — as far as I'm aware — `.css` and `.postcss`.

**Comment by Agedjus** [comment]
Hi, I just noticed it works for the SvelteKit demo app but no for the skeleton template

> ~/code/website$ npx svelte-add tailwindcss
> ➕ Svelte Add
> The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.
> 
> postcss
>   ❌ `postcss` is installed
>   ❌ `postcss-load-config` is installed
>   ✅ `svelte-preprocess` reads PostCSS config implicitly in `svelte.config.js`
>   ❌ `postcss.config.cjs` exists and `postcss.config.js` does not exist
>   ❌ `src/app.postcss` exists
>   ❌ The main file (`src/routes/__layout.svelte` for SvelteKit, `src/main.js` or `src/main.ts` for Vite) imports `src/app.postcss`
> 
>   ❌ seems to have been partially set up before running this command in a way that can't be automatically fixed? (see above)

**Comment by babichjacob** [comment]
> Hi, I just noticed it works for the SvelteKit demo app but no for the skeleton template

What was in your `svelte.config.js` file before running this command? That one having the ✅ surprises me.

On my own computer, I've tried this just now and it worked.
